version: '3.0'

volumes:
  cache:
    driver: local
  db-data:
    driver: local
  minio-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
      - minio
      - redis
    env_file:
      - .env
    ports:
      - '8080:8080'

  db:
    image: 'postgres:15.1-alpine'
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio